apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
    tier: database
  name: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      # Changed to 5.7 to obtain native ARM64 support for Apple Silicon Macs
      - image: mysql:5.7.44 
        name: mysql
        args: ["--performance_schema=OFF"] 
        env:
        - name: MYSQL_DATABASE
          value: pricelist
        - name: MYSQL_PASSWORD
          value: pricelist
        - name: MYSQL_USER
          value: pricelist
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-db
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "800m"
      volumes:
      - name: mysql-db
        persistentVolumeClaim:
          claimName: pricelist-db-pvc
